version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: car_renting_backend
    container_name: car_renting_backend_c
    networks:
      - ahp-spezprog-network
    ports:
      - 80:4000

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    image: car_renting_webapp
    container_name: car_renting_webapp_c
    networks:
      - ahp-spezprog-network
    ports:
      - 81:80

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=test
    ports:
      - 27017:27017
    networks:
      - ahp-spezprog-network
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - ahp-spezprog-network

volumes:
  mongo-data:


networks:
  ahp-spezprog-network: